[2024-09-22T16:53:51.702+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T16:53:51.719+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emp_dag.emp_data_load scheduled__2024-09-21T00:00:00+00:00 [queued]>
[2024-09-22T16:53:51.728+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emp_dag.emp_data_load scheduled__2024-09-21T00:00:00+00:00 [queued]>
[2024-09-22T16:53:51.729+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-22T16:53:51.746+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): emp_data_load> on 2024-09-21 00:00:00+00:00
[2024-09-22T16:53:51.760+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'emp_dag', 'emp_data_load', 'scheduled__2024-09-21T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/emp_dag.py', '--cfg-path', '/tmp/tmpbeh59tjp']
[2024-09-22T16:53:51.762+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask emp_data_load
[2024-09-22T16:53:51.766+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=280) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T16:53:51.767+0000] {standard_task_runner.py:72} INFO - Started process 282 to run task
[2024-09-22T16:53:51.831+0000] {task_command.py:467} INFO - Running <TaskInstance: emp_dag.emp_data_load scheduled__2024-09-21T00:00:00+00:00 [running]> on host 3ac4fa004d82
[2024-09-22T16:53:51.968+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***_SS' AIRFLOW_CTX_DAG_ID='emp_dag' AIRFLOW_CTX_TASK_ID='emp_data_load' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-21T00:00:00+00:00'
[2024-09-22T16:53:51.971+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-22T16:53:51.972+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-22T16:53:51.973+0000] {logging_mixin.py:190} INFO - Current task name:emp_data_load state:running start_date:2024-09-22 16:53:51.720099+00:00
[2024-09-22T16:53:51.974+0000] {logging_mixin.py:190} INFO - Dag name:emp_dag and current dag run status:running
[2024-09-22T16:53:51.975+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T16:53:51.977+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-22T16:53:51.979+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/beam_scripts/emp_data_load.py']
[2024-09-22T16:53:52.000+0000] {subprocess.py:86} INFO - Output:
[2024-09-22T16:53:58.213+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-22T16:53:58.213+0000] {subprocess.py:93} INFO -   File "/opt/***/beam_scripts/emp_data_load.py", line 124, in <module>
[2024-09-22T16:53:58.216+0000] {subprocess.py:93} INFO -     hello_pubsub()
[2024-09-22T16:53:58.216+0000] {subprocess.py:93} INFO -   File "/opt/***/beam_scripts/emp_data_load.py", line 89, in hello_pubsub
[2024-09-22T16:53:58.217+0000] {subprocess.py:93} INFO -     client = storage.Client(project=project_id)
[2024-09-22T16:53:58.217+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-22T16:53:58.218+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/google/cloud/storage/client.py", line 227, in __init__
[2024-09-22T16:53:58.218+0000] {subprocess.py:93} INFO -     super(Client, self).__init__(
[2024-09-22T16:53:58.218+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/google/cloud/client/__init__.py", line 321, in __init__
[2024-09-22T16:53:58.218+0000] {subprocess.py:93} INFO -     Client.__init__(
[2024-09-22T16:53:58.219+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/google/cloud/client/__init__.py", line 178, in __init__
[2024-09-22T16:53:58.219+0000] {subprocess.py:93} INFO -     credentials, _ = google.auth.default(scopes=scopes)
[2024-09-22T16:53:58.220+0000] {subprocess.py:93} INFO -                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-22T16:53:58.220+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/google/auth/_default.py", line 691, in default
[2024-09-22T16:53:58.220+0000] {subprocess.py:93} INFO -     raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
[2024-09-22T16:53:58.220+0000] {subprocess.py:93} INFO - google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2024-09-22T16:53:58.617+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-22T16:53:58.635+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-22T16:53:58.660+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-22T16:53:58.661+0000] {logging_mixin.py:190} INFO - Task start:2024-09-22 16:53:51.720099+00:00 end:2024-09-22 16:53:58.659940+00:00 duration:6.939841
[2024-09-22T16:53:58.661+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): emp_data_load> dag:<DAG: emp_dag> dagrun:<DagRun emp_dag @ 2024-09-21 00:00:00+00:00: scheduled__2024-09-21T00:00:00+00:00, state:running, queued_at: 2024-09-22 16:52:35.626655+00:00. externally triggered: False>
[2024-09-22T16:53:58.662+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-09-22T16:53:58.662+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=emp_dag, task_id=emp_data_load, run_id=scheduled__2024-09-21T00:00:00+00:00, execution_date=20240921T000000, start_date=20240922T165351, end_date=20240922T165358
[2024-09-22T16:53:58.684+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T16:53:58.685+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task emp_data_load (Bash command failed. The command returned a non-zero exit code 1.; 282)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-22T16:53:58.709+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-22T16:53:58.728+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T16:53:58.733+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-09-22T17:09:54.597+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T17:09:54.615+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emp_dag.emp_data_load scheduled__2024-09-21T00:00:00+00:00 [queued]>
[2024-09-22T17:09:54.623+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emp_dag.emp_data_load scheduled__2024-09-21T00:00:00+00:00 [queued]>
[2024-09-22T17:09:54.624+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-22T17:09:54.643+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): emp_data_load> on 2024-09-21 00:00:00+00:00
[2024-09-22T17:09:54.653+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T17:09:54.655+0000] {standard_task_runner.py:72} INFO - Started process 239 to run task
[2024-09-22T17:09:54.655+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'emp_dag', 'emp_data_load', 'scheduled__2024-09-21T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/emp_dag.py', '--cfg-path', '/tmp/tmpis_81kh2']
[2024-09-22T17:09:54.656+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask emp_data_load
[2024-09-22T17:09:54.723+0000] {task_command.py:467} INFO - Running <TaskInstance: emp_dag.emp_data_load scheduled__2024-09-21T00:00:00+00:00 [running]> on host 47d21d915938
[2024-09-22T17:09:54.819+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***_SS' AIRFLOW_CTX_DAG_ID='emp_dag' AIRFLOW_CTX_TASK_ID='emp_data_load' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-21T00:00:00+00:00'
[2024-09-22T17:09:54.821+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-22T17:09:54.822+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-22T17:09:54.823+0000] {logging_mixin.py:190} INFO - Current task name:emp_data_load state:running start_date:2024-09-22 17:09:54.615809+00:00
[2024-09-22T17:09:54.823+0000] {logging_mixin.py:190} INFO - Dag name:emp_dag and current dag run status:running
[2024-09-22T17:09:54.824+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T17:09:54.825+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-22T17:09:54.826+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/beam_scripts/emp_data_load.py']
[2024-09-22T17:09:54.843+0000] {subprocess.py:86} INFO - Output:
[2024-09-22T17:10:16.604+0000] {subprocess.py:93} INFO - /opt/***/beam_scripts/emp_data_load.py:70: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
[2024-09-22T17:10:16.605+0000] {subprocess.py:93} INFO -   "processing_timestamp": datetime.utcnow().isoformat() + "Z"
[2024-09-22T17:10:34.799+0000] {subprocess.py:93} INFO - Service account key path set to: /opt/***/cred/gcp-test.json
[2024-09-22T17:10:34.800+0000] {subprocess.py:93} INFO - Table aceinternal-2ed449d3.sandbox_ss_eu.sample_test_1 exists.
[2024-09-22T17:10:34.801+0000] {subprocess.py:93} INFO - New 1 files appended
[2024-09-22T17:10:35.222+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-22T17:10:35.258+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T17:10:35.259+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=emp_dag, task_id=emp_data_load, run_id=scheduled__2024-09-21T00:00:00+00:00, execution_date=20240921T000000, start_date=20240922T170954, end_date=20240922T171035
[2024-09-22T17:10:35.274+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-09-22T17:10:35.275+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-09-22T17:10:35.275+0000] {logging_mixin.py:190} INFO - Dag name:emp_dag queued_at:2024-09-22 17:08:46.838652+00:00
[2024-09-22T17:10:35.276+0000] {logging_mixin.py:190} INFO - Task hostname:47d21d915938 operator:BashOperator
[2024-09-22T17:10:35.318+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-22T17:10:35.339+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T17:10:35.344+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
